name: Auto Semver
runs:
  using: node20
  main: dist/main.js
inputs:
  # Settings
  token:
    required: false
  type:
    required: false
  refuse_major_increment:
    required: false
  increment:
    required: false
  hard:
    required: false
outputs:
  version:
    description: |
      The new version.
  tag:
    description: |
      The tag that should be created in the workflow.
  branch:
    description: |
      The name of the branch that should be created for the current
      latest version. Defaults to `"none"` if a release branch should
      not be created.
  branch_sha:
    description: |
      The commit SHA the branch should origin from.
